#ifndef QTLIBTORRENT_GLOBAL_H
#define QTLIBTORRENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTLIBTORRENT_LIBRARY)
#  define QTLIBTORRENTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTLIBTORRENTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTLIBTORRENT_GLOBAL_H
