ROXEE_PROJECT_NAME = RoxeeTorrent
ROXEE_VENDOR_NAME = WebItUp
ROXEE_PROJECT_VERSION_MAJOR = 1
ROXEE_PROJECT_VERSION_MINOR = 0
ROXEE_PROJECT_VERSION_BUGFIX = 0
ROXEE_MINIMUM_QT = 4.6
ROXEE_MIN_OSX = 10.6

# Name of the target
TARGET = roxeetorrent
